document.write(
    "<div class=\"navbar navbar-default\" role=\"navigation\" id=\"header\">"
    + "    <div class=\"content\">"
    + "        <div class=\"navbar-header\">"
    + "            <button class=\"navbar-toggle\" type=\"button\" data-toggle=\"collapse\" data-target=\".navbar-responsive-collapse\">"
    + "                <span class=\"icon-bar\"></span>"
    + "                <span class=\"icon-bar\"></span>"
    + "                <span class=\"icon-bar\"></span>"
    + "            </button>"
    + "            <div class=\"logo\">"
    + "                <a href=\"#\"><img src=\"images/logo.png\" /></a>"
    + "            </div>"
    + "        </div>"
    + "        <div class=\"collapse navbar-collapse navbar-responsive-collapse\">"
    + "            <ul id=\"nav\">"
    + "                <li><a id=\"index\" href=\"index.html\">首页</a></li>"
    + "                <li><a id=\"parters\" href=\"parters.html\">合作机构</a></li>"
    + "                <li><a id=\"aboutus\" href=\"aboutus.html\">关于杏缘</a></li>"
    + "                <li><a id=\"team\" href=\"team.html\">团队介绍</a></li>"
    + "                <li><a id=\"contactus\" href=\"contactus.html\">联系我们</a></li>"
    + "                <li><a id=\"joinus\" href=\"joinus.html\">加入我们</a></li>"
    + "            </ul>"
    + "        </div>"
    + "    </div>"
    + "</div>"
);